In [1]:
import pandas as pd
from ecos import Ecos
service_key = ""
api = Ecos(service_key)

In [41]:
quarter_to_month = {'Q1': '03-01', 'Q2': '06-01', 'Q3': '09-01', 'Q4': '12-01'}
def convert_to_datetime(df, cycle):
    if cycle == 'Q':
        return pd.to_datetime(df.str[:4] + '-' + df.str[4:].map(quarter_to_month), format='%Y-%m-%d')
    elif cycle == 'M':
        return pd.to_datetime(df.str[:4] + '-' + df.str[4:] + '-01', format='%Y-%m-%d')
    elif cycle == 'D':
        return pd.to_datetime(df.str[:4] + '-' + df.str[4:6] + '-' + df.str[6:], format='%Y-%m-%d')
    elif cycle == 'A':
        return pd.to_datetime(df.str[:4] + '-12-01', format='%Y-%m-%d')
    
def return_final_df(df, cycle, var_name):
    df['TIME'] = convert_to_datetime(df['TIME'], cycle)
    df.rename(columns={"DATA_VALUE":var_name}, inplace=True)
    df = pd.DataFrame(df, columns=["TIME", var_name])
    df.set_index("TIME", drop=True, append=False, inplace=True)
    return df

# 1. economy 테이블

In [5]:
c_200Y002 = api.get_statistic_item_list(통계표코드="200Y002")
c_200Y002

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10111,"국내총생산(GDP)(실질, 계절조정, 전기비)",1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
1,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10112,비농림어업GDP,1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
2,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10113,농림어업,1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
3,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10114,제조업,1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
4,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10115,건설업,1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
5,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10116,서비스업,1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
6,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10117,ICT산업,1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1995Q2,2023Q3,114,%,None
7,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10118,비ICT산업,1011,"경제활동별 성장률(실질, 계절조정, 전기비)",Q,1995Q2,2023Q3,114,%,None
8,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10121,"국내총생산에 대한 지출(실질, 계절조정, 전기비)",1012,"지출항목별 증감률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
9,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10122,민간소비,1012,"지출항목별 증감률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
10,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10123,설비투자,1012,"지출항목별 증감률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
11,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10124,건설투자,1012,"지출항목별 증감률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
12,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10125,재화수출,1012,"지출항목별 증감률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
13,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10126,재화수입,1012,"지출항목별 증감률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
14,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10127,내수(재고제외),1012,"지출항목별 증감률(실질, 계절조정, 전기비)",Q,1960Q2,2023Q3,254,%,None
15,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10211,"국내총생산(GDP)(실질, 원계열, 전년동기비)",1021,"경제활동별 성장률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
16,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10212,농림어업,1021,"경제활동별 성장률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
17,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10213,제조업,1021,"경제활동별 성장률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
18,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10214,"전기, 가스 및 수도사업",1021,"경제활동별 성장률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
19,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10215,건설업,1021,"경제활동별 성장률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
20,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10216,서비스업,1021,"경제활동별 성장률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
21,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10221,"국내총생산에 대한 지출(실질, 원계열, 전년동기비)",1022,"지출항목별 증감률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
22,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10222,민간소비,1022,"지출항목별 증감률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
23,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10223,설비투자,1022,"지출항목별 증감률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
24,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10224,건설투자,1022,"지출항목별 증감률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
25,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10225,재화수출,1022,"지출항목별 증감률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
26,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10226,재화수입,1022,"지출항목별 증감률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
27,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,10227,내수(재고제외),1022,"지출항목별 증감률(실질, 원계열, 전년동기비)",Q,1961Q1,2023Q3,251,%,None
28,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,20111,명목 GNI(전기비),2011,계절조정(전기비),Q,1960Q2,2023Q3,254,%,None
29,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,20112,실질 GNI(전기비),2011,계절조정(전기비),Q,1960Q2,2023Q3,254,%,None
30,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,20121,명목 GNI(전년동기비),2012,원계열(전년동기비),Q,1961Q1,2023Q3,251,%,None
31,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,20122,실질 GNI(전년동기비),2012,원계열(전년동기비),Q,1961Q1,2023Q3,251,%,None
32,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,301,"GDP 디플레이터 등락률(원계열, 전년동기비)",None,None,Q,1961Q1,2023Q3,251,%,None
33,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,40101,총저축률,401,"총저축 및 총투자(명목, 계절조정)",Q,1970Q1,2023Q3,215,%,None
34,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,40102,국내총투자율,401,"총저축 및 총투자(명목, 계절조정)",Q,1970Q1,2023Q3,215,%,None
35,200Y002,2.1.1.2. 주요지표(분기지표),Group1,계정항목,501,"수출입의 대 GNI 비율(명목, 계절조정)",None,None,Q,1960Q1,2023Q3,255,%,None

In [78]:
real_GDP = api.get_statistic_search(통계표코드="200Y002", 주기="Q", 검색시작일자="1960Q2", 검색종료일자="2023Q3", 통계항목코드1="10111", translate=False)
real_GDP = return_final_df(real_GDP, "Q", "real_GDP")
real_GDP.tail()

           real_GDP
TIME
2022-09-01      0.2
2022-12-01     -0.3
2023-03-01      0.3
2023-06-01      0.6
2023-09-01      0.6

In [3]:
GDP_deflator_rate = api.get_statistic_search(통계표코드="200Y002", 주기="Q", 검색시작일자="1961Q1", 검색종료일자="2023Q3", 통계항목코드1="301", translate=False)
GDP_deflator_rate = return_final_df(GDP_deflator_rate, "Q", "GDP_deflator_rate")
GDP_deflator_rate.tail()

           GDP_deflator_rate
TIME
2022-09-01               0.1
2022-12-01               0.4
2023-03-01               1.4
2023-06-01               0.5
2023-09-01               2.8

In [4]:
# c_901Y067 = api.get_statistic_item_list(통계표코드="901Y067")
# c_901Y067
leading_composite_index = api.get_statistic_search(통계표코드="901Y067", 주기="M", 검색시작일자="197001", 검색종료일자="202310", 통계항목코드1="I16A", translate=False)
leading_composite_index = return_final_df(leading_composite_index, "M", "leading_composite_index")
leading_composite_index.tail()

           leading_composite_index
TIME
2023-06-01                   110.5
2023-07-01                   111.1
2023-08-01                   111.4
2023-09-01                   111.9
2023-10-01                   112.4

In [11]:
word_901Y067 = api.get_statistic_word(용어="경기종합지수")
word_901Y067['용어설명'].values[0]

'국민경제 전체의 경기동향을 쉽게 파악하기 위하여 경제부문별(생산, 투자, 고용, 소비 등)로 경기에 민감하게 반영하는 주요 경제지표들을 선정한 후 이 지표들의 전월대비 증감률을 합성하여 작성하는데, 개별 구성지표들의 증감률 크기에 의해 경기변동의 진폭까지도 알 수 있으므로 경기변동의 방향, 국면 및 전환점은 물론 속도까지도 동시에 분석할 수 있어 우리나라의 대표적인 종합경기지표로 널리 활용되고 있다. 경기종합지수에는 선행(Leading), 동행(Coincident), 후행(Lagging)종합지수가 있다. 선행종합지수는 앞으로의 경기동향을 예측하는 지표로서 구인구직비율, 기계수주액(국내), 건설수주액, 총유동성 등과 같이 앞으로 일어날 경제현상을 미리 알려주는 10개 지표들의 움직임을 종합하여 작성한다. 동행종합지수는 현재의 경기상태를 나타내는 지표로서 산업생산지수, 제조업가동률지수, 도소매판매액지수, 비농가취업자수 등과 같이 국민경제 전체의 경기변동과 거의 동일한 방향으로 움직이는 8개 지표로 구성된다. 후행종합지수는 경기의 변동을 사후에 확인하는 지표로서 생산자제품재고지수, 회사채유통수익률, 가계소비지출 등과 같은 6개 지표로 구성된다.'

In [81]:
coincident_composite_index = api.get_statistic_search(통계표코드="901Y067", 주기="M", 검색시작일자="197001", 검색종료일자="202310", 통계항목코드1="I16B", translate=False)
coincident_composite_index = return_final_df(coincident_composite_index, "M", "coincident_composite_index")
coincident_composite_index.tail()

           coincident_composite_index
TIME
2023-06-01                      110.3
2023-07-01                        110
2023-08-01                        110
2023-09-01                        110
2023-10-01                      110.1

In [82]:
leading_composite_rate = api.get_statistic_search(통계표코드="901Y067", 주기="M", 검색시작일자="197001", 검색종료일자="202310", 통계항목코드1="I16E", translate=False)
leading_composite_rate = return_final_df(leading_composite_rate, "M", "leading_composite_rate")
leading_composite_rate.tail()

           leading_composite_rate
TIME
2023-06-01                   98.9
2023-07-01                   99.3
2023-08-01                   99.3
2023-09-01                   99.4
2023-10-01                   99.7

In [5]:
coincident_composite_rate = api.get_statistic_search(통계표코드="901Y067", 주기="M", 검색시작일자="197001", 검색종료일자="202310", 통계항목코드1="I16D", translate=False)
coincident_composite_rate = return_final_df(coincident_composite_rate, "M", "leading_composite_rate")
coincident_composite_rate.tail()

           leading_composite_rate
TIME
2023-06-01                  100.1
2023-07-01                   99.6
2023-08-01                   99.4
2023-09-01                   99.2
2023-10-01                   99.1

In [85]:
# real_GDP.join(GDP_deflator_rate, on='TIME', how='outer')
# real_GDP
# economy.rename(index={"TIME":"date"}, inplace=False)
# economy = real_GDP
# for df in [GDP_deflator_rate, leading_composite_index, coincident_composite_index, leading_composite_rate, coincident_composite_rate]:
#     economy = pd.merge(economy, df, on='TIME', how='inner')
# economy

# economy.csv 완성
economy = pd.concat([real_GDP, GDP_deflator_rate, leading_composite_index, coincident_composite_index, leading_composite_rate, coincident_composite_rate], axis=1)
economy.to_csv("economy.csv")

# 2. bank_finance 테이블

In [97]:
# 삭제한 값
# c_104Y010 = api.get_statistic_item_list(통계표코드="104Y010")
# c_104Y010
# fixed_deposit = api.get_statistic_search(통계표코드="104Y010", 주기="Q", 검색시작일자="1995Q1", 검색종료일자="2023Q3", 통계항목코드1="1000000", translate=False)
# fixed_deposit['TIME'] = convert_to_datetime(fixed_deposit['TIME'], 'Q')
# fixed_deposit.rename(columns={"DATA_VALUE":"fixed_deposit"}, inplace=True)
# fixed_deposit = pd.DataFrame(fixed_deposit, columns=["TIME", 'fixed_deposit'])
# fixed_deposit.set_index("TIME", drop=True, append=False, inplace=True)
# fixed_deposit.tail()

In [98]:
c_151Y004 = api.get_statistic_item_list(통계표코드="151Y004")
c_151Y004

# 가계신용
household_credit = api.get_statistic_search(통계표코드="151Y004", 주기="Q", 검색시작일자="2005Q4", 검색종료일자="2023Q3", 통계항목코드1="11100A0", translate=False)
household_credit = return_final_df(household_credit, "Q", "household_credit")
household_credit.tail()

           household_credit
TIME
2022-09-01         748963.9
2022-12-01         754831.1
2023-03-01         750175.6
2023-06-01         753906.8
2023-09-01           764776

In [141]:
# c_104Y017 = api.get_statistic_item_list(통계표코드="104Y017")
# c_104Y017

# 예금 회전율-요구불예금
demand_deposit_turnover_rate = api.get_statistic_search(통계표코드="104Y017", 주기="M", 검색시작일자="198501", 검색종료일자="202309", 통계항목코드1="BDFA1", translate=False)
demand_deposit_turnover_rate = return_final_df(demand_deposit_turnover_rate, "M", "demand_deposit_turnover_rate")
demand_deposit_turnover_rate.tail()

           demand_deposit_turnover_rate
TIME
2023-05-01                         16.3
2023-06-01                         17.4
2023-07-01                         17.5
2023-08-01                         17.2
2023-09-01                         16.9

In [140]:
# 예금 회전율-저축성예금
saving_deposit_turnover_rate = api.get_statistic_search(통계표코드="104Y017", 주기="M", 검색시작일자="198501", 검색종료일자="202309", 통계항목코드1="BDFA2", translate=False)  #통계항목코드1=""
saving_deposit_turnover_rate = return_final_df(saving_deposit_turnover_rate, "M", "saving_deposit_turnover_rate")
saving_deposit_turnover_rate.tail()

           saving_deposit_turnover_rate
TIME
2023-05-01                          1.3
2023-06-01                          1.3
2023-07-01                          1.4
2023-08-01                          1.3
2023-09-01                          1.3

In [139]:
# c_722Y001 = api.get_statistic_item_list(통계표코드="722Y001")
# c_722Y001

# 한국은행 기준금리
standard_interest_rate = api.get_statistic_search(통계표코드="722Y001", 주기="D", 검색시작일자="19990506", 검색종료일자="20231204", 통계항목코드1="0101000", translate=False)
standard_interest_rate = return_final_df(standard_interest_rate, "D", "standard_interest_rate")
standard_interest_rate.tail() #8978

           standard_interest_rate
TIME
2023-11-30                    3.5
2023-12-01                    3.5
2023-12-02                    3.5
2023-12-03                    3.5
2023-12-04                    3.5

In [125]:
# c_902Y006 = api.get_statistic_item_list(통계표코드="902Y006")
# c_902Y006
usa_interest_rate = api.get_statistic_search(통계표코드="902Y006", 주기="M", 검색시작일자="195407", 검색종료일자="202310", 통계항목코드1="US", translate=False)
usa_interest_rate = return_final_df(usa_interest_rate, "M", "usa_interest_rate") #832
usa_interest_rate.tail()

           usa_interest_rate
TIME
2023-06-01             5.125
2023-07-01             5.375
2023-08-01             5.375
2023-09-01             5.375
2023-10-01             5.375

In [126]:
c_121Y002 = api.get_statistic_item_list(통계표코드="121Y002")
c_121Y002

# 예금은행 수신금리 - 신규취급액 기준
saving_interest_rate_new = api.get_statistic_search(통계표코드="121Y002", 주기="M", 검색시작일자="199601", 검색종료일자="202310", 통계항목코드1="BEABAA21", translate=False)
saving_interest_rate_new = return_final_df(saving_interest_rate_new, "M", "saving_interest_rate_new") #832
saving_interest_rate_new.tail()

           saving_interest_rate_new
TIME
2023-06-01                     3.65
2023-07-01                     3.63
2023-08-01                     3.59
2023-09-01                     3.74
2023-10-01                     3.91

In [127]:
# c_121Y013 = api.get_statistic_item_list(통계표코드="121Y013")
# c_121Y013

# 예금은행 수신금리 - 잔액 기준
saving_interest_rate_balance = api.get_statistic_search(통계표코드="121Y013", 주기="M", 검색시작일자="200109", 검색종료일자="202310", 통계항목코드1="BEABAB211", translate=False)
saving_interest_rate_balance = return_final_df(saving_interest_rate_balance, "M", "saving_interest_rate_balance") #832
saving_interest_rate_balance.tail()

           saving_interest_rate_balance
TIME
2023-06-01                         3.87
2023-07-01                         3.89
2023-08-01                         3.91
2023-09-01                         3.92
2023-10-01                         3.92

In [96]:
c_121Y006 = api.get_statistic_item_list(통계표코드="121Y006")
c_121Y006

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA01,대출평균 1),BECBLA,신규취급액 기준,A,1996,2022,27,연%,None
1,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA01,대출평균 1),BECBLA,신규취급액 기준,M,199601,202310,334,연%,None
2,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA01,대출평균 1),BECBLA,신규취급액 기준,Q,1996Q1,2023Q3,111,연%,None
3,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA02,기업대출,BECBLA01,대출평균 1),A,1996,2022,27,연리%,None
4,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA02,기업대출,BECBLA01,대출평균 1),M,199601,202310,334,연리%,None
5,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA02,기업대출,BECBLA01,대출평균 1),Q,1996Q1,2023Q3,111,연리%,None
6,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0201,대기업대출,BECBLA02,기업대출,A,1996,2022,27,연리%,None
7,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0201,대기업대출,BECBLA02,기업대출,M,199601,202310,334,연리%,None
8,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0201,대기업대출,BECBLA02,기업대출,Q,1996Q1,2023Q3,111,연리%,None
9,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0202,중소기업대출,BECBLA02,기업대출,A,1996,2022,27,연리%,None
10,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0202,중소기업대출,BECBLA02,기업대출,M,199601,202310,334,연리%,None
11,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0202,중소기업대출,BECBLA02,기업대출,Q,1996Q1,2023Q3,111,연리%,None
12,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0203,운전자금대출,BECBLA02,기업대출,A,1996,2022,27,연리%,None
13,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0203,운전자금대출,BECBLA02,기업대출,M,199601,202310,334,연리%,None
14,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0203,운전자금대출,BECBLA02,기업대출,Q,1996Q1,2023Q3,111,연리%,None
15,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0204,시설자금대출,BECBLA02,기업대출,A,1996,2022,27,연리%,None
16,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0204,시설자금대출,BECBLA02,기업대출,M,199601,202310,334,연리%,None
17,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0204,시설자금대출,BECBLA02,기업대출,Q,1996Q1,2023Q3,111,연리%,None
18,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03,가계대출,BECBLA01,대출평균 1),A,1996,2022,27,연리%,None
19,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03,가계대출,BECBLA01,대출평균 1),M,199601,202310,334,연리%,None
20,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03,가계대출,BECBLA01,대출평균 1),Q,1996Q1,2023Q3,111,연리%,None
21,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0301,소액대출 (500만원 이하),BECBLA03,가계대출,A,2001,2022,22,연리%,None
22,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0301,소액대출 (500만원 이하),BECBLA03,가계대출,M,200109,202310,266,연리%,None
23,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0301,소액대출 (500만원 이하),BECBLA03,가계대출,Q,2001Q4,2023Q3,88,연리%,None
24,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0302,주택담보대출,BECBLA03,가계대출,A,2001,2022,22,연리%,None
25,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0302,주택담보대출,BECBLA03,가계대출,M,200109,202310,266,연리%,None
26,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0302,주택담보대출,BECBLA03,가계대출,Q,2001Q4,2023Q3,88,연리%,None
27,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0303,예·적금담보대출,BECBLA03,가계대출,A,2001,2022,22,연리%,None
28,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0303,예·적금담보대출,BECBLA03,가계대출,M,200109,202310,266,연리%,None
29,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0303,예·적금담보대출,BECBLA03,가계대출,Q,2001Q4,2023Q3,88,연리%,None
30,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0304,보증대출,BECBLA03,가계대출,A,2001,2022,22,연리%,None
31,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0304,보증대출,BECBLA03,가계대출,M,200109,202310,266,연리%,None
32,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA0304,보증대출,BECBLA03,가계대출,Q,2001Q4,2023Q3,88,연리%,None
33,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03051,일반신용대출 2),BECBLA03,가계대출,A,2005,2022,18,연리%,None
34,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03051,일반신용대출 2),BECBLA03,가계대출,M,200410,202310,229,연리%,None
35,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03051,일반신용대출 2),BECBLA03,가계대출,Q,2004Q4,2023Q3,76,연리%,None
36,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03052,집단대출 2),BECBLA03,가계대출,A,2005,2022,18,연리%,None
37,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03052,집단대출 2),BECBLA03,가계대출,M,200410,202310,229,연리%,None
38,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03052,집단대출 2),BECBLA03,가계대출,Q,2004Q4,2023Q3,76,연리%,None
39,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA04,공공및기타부문대출,BECBLA01,대출평균 1),A,1996,2022,27,연리%,None
40,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA04,공공및기타부문대출,BECBLA01,대출평균 1),M,199601,202310,334,연리%,None
41,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA04,공공및기타부문대출,BECBLA01,대출평균 1),Q,1996Q1,2023Q3,111,연리%,None
42,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA05,상업어음할인,BECBLA02,기업대출,A,1996,2022,27,연리%,None
43,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA05,상업어음할인,BECBLA02,기업대출,M,199601,202310,334,연리%,None
44,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA05,상업어음할인,BECBLA02,기업대출,Q,1996Q1,2023Q3,111,연리%,None
45,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA07,기업일반자금대출,BECBLA02,기업대출,A,1996,2022,27,연리%,None
46,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA07,기업일반자금대출,BECBLA02,기업대출,M,199601,202310,334,연리%,None
47,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA07,기업일반자금대출,BECBLA02,기업대출,Q,1996Q1,2023Q3,111,연리%,None
48,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA030201,고정형 주택담보대출,BECBLA0302,주택담보대출,A,2013,2022,10,연리%,None
49,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA030201,고정형 주택담보대출,BECBLA0302,주택담보대출,M,201301,202310,130,연리%,None
50,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA030201,고정형 주택담보대출,BECBLA0302,주택담보대출,Q,2013Q1,2023Q3,43,연리%,None
51,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA030202,변동형 주택담보대출,BECBLA0302,주택담보대출,A,2013,2022,10,연리%,None
52,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA030202,변동형 주택담보대출,BECBLA0302,주택담보대출,M,201301,202310,130,연리%,None
53,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA030202,변동형 주택담보대출,BECBLA0302,주택담보대출,Q,2013Q1,2023Q3,43,연리%,None
54,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03041,전세자금대출,BECBLA0304,보증대출,A,2015,2022,8,연리%,None
55,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03041,전세자금대출,BECBLA0304,보증대출,M,201501,202310,106,연리%,None
56,121Y006,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),Group1,계정항목,BECBLA03041,전세자금대출,BECBLA0304,보증대출,Q,2015Q1,2023Q3,35,연리%,None

In [128]:
# 예금은행 대출금리 - 신규취급액 기준 - 고정형주택담보대출
fixed_loan_interest_rate_new = api.get_statistic_search(통계표코드="121Y006", 주기="M", 검색시작일자="201301", 검색종료일자="202310", 통계항목코드1="BECBLA030201", translate=False)
fixed_loan_interest_rate_new = return_final_df(fixed_loan_interest_rate_new, "M", "fixed_loan_interest_rate_new")
fixed_loan_interest_rate_new.tail()

           fixed_loan_interest_rate_new
TIME
2023-06-01                          4.2
2023-07-01                         4.22
2023-08-01                         4.25
2023-09-01                          4.3
2023-10-01                         4.53

In [129]:
# 예금은행 대출금리 - 신규취급액 기준 - 변동형주택담보대출
variable_loan_interest_rate_new = api.get_statistic_search(통계표코드="121Y006", 주기="M", 검색시작일자="201301", 검색종료일자="202310", 통계항목코드1="BECBLA030202", translate=False)
variable_loan_interest_rate_new = return_final_df(variable_loan_interest_rate_new, "M", "variable_loan_interest_rate_new")
variable_loan_interest_rate_new.tail()

           variable_loan_interest_rate_new
TIME
2023-06-01                            4.41
2023-07-01                            4.45
2023-08-01                             4.5
2023-09-01                            4.51
2023-10-01                            4.64

In [131]:
# 예금은행 대출금리 - 신규취급액 기준 - 전세자금대출
lease_loan_interest_rate_new = api.get_statistic_search(통계표코드="121Y006", 주기="M", 검색시작일자="201501", 검색종료일자="202310", 통계항목코드1="BECBLA03041", translate=False)
lease_loan_interest_rate_new = return_final_df(lease_loan_interest_rate_new, "M", "lease_loan_interest_rate_new")
lease_loan_interest_rate_new.tail()

           lease_loan_interest_rate_new
TIME
2023-06-01                         4.14
2023-07-01                         4.14
2023-08-01                         4.13
2023-09-01                         4.18
2023-10-01                         4.28

In [93]:
c_121Y015 = api.get_statistic_item_list(통계표코드="121Y015")
c_121Y015

,통계표코드,통계명,항목그룹코드,항목그룹명,통계항목코드,통계항목명,상위통계항목코드,상위통계항목명,시점,수록시작일자,수록종료일자,자료수,단위,가중치
0,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB01,총대출 1),BECBLB,잔액 기준,A,2001,2022,22,연리%,None
1,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB01,총대출 1),BECBLB,잔액 기준,M,200109,202310,266,연리%,None
2,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB01,총대출 1),BECBLB,잔액 기준,Q,2001Q3,2023Q3,89,연리%,None
3,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB02,총대출(당좌대출 제외),BECBLB,잔액 기준,A,2001,2022,22,연리%,None
4,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB02,총대출(당좌대출 제외),BECBLB,잔액 기준,M,200109,202310,266,연리%,None
5,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB02,총대출(당좌대출 제외),BECBLB,잔액 기준,Q,2001Q3,2023Q3,89,연리%,None
6,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB0201,기업대출 2),BECBLB01,총대출 1),A,2001,2022,22,연리%,None
7,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB0201,기업대출 2),BECBLB01,총대출 1),M,200109,202310,266,연리%,None
8,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB0201,기업대출 2),BECBLB01,총대출 1),Q,2001Q3,2023Q3,89,연리%,None
9,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020101,대기업대출,BECBLB0201,기업대출 2),A,2001,2022,22,연리%,None
10,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020101,대기업대출,BECBLB0201,기업대출 2),M,200109,202310,266,연리%,None
11,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020101,대기업대출,BECBLB0201,기업대출 2),Q,2001Q3,2023Q3,89,연리%,None
12,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020102,중소기업대출,BECBLB0201,기업대출 2),A,2001,2022,22,연리%,None
13,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020102,중소기업대출,BECBLB0201,기업대출 2),M,200109,202310,266,연리%,None
14,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020102,중소기업대출,BECBLB0201,기업대출 2),Q,2001Q3,2023Q3,89,연리%,None
15,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020103,운전자금대출,BECBLB0201,기업대출 2),A,2001,2022,22,연리%,None
16,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020103,운전자금대출,BECBLB0201,기업대출 2),M,200109,202310,266,연리%,None
17,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020103,운전자금대출,BECBLB0201,기업대출 2),Q,2001Q3,2023Q3,89,연리%,None
18,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020104,시설자금대출,BECBLB0201,기업대출 2),A,2001,2022,22,연리%,None
19,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020104,시설자금대출,BECBLB0201,기업대출 2),M,200109,202310,266,연리%,None
20,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020104,시설자금대출,BECBLB0201,기업대출 2),Q,2001Q3,2023Q3,89,연리%,None
21,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB0202,가계대출 2),BECBLB01,총대출 1),A,2001,2022,22,연리%,None
22,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB0202,가계대출 2),BECBLB01,총대출 1),M,200109,202310,266,연리%,None
23,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB0202,가계대출 2),BECBLB01,총대출 1),Q,2001Q3,2023Q3,89,연리%,None
24,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020201,소액대출 (500만원 이하),BECBLB0202,가계대출 2),A,2001,2022,22,연리%,None
25,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020201,소액대출 (500만원 이하),BECBLB0202,가계대출 2),M,200109,202310,266,연리%,None
26,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020201,소액대출 (500만원 이하),BECBLB0202,가계대출 2),Q,2001Q3,2023Q3,89,연리%,None
27,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020202,주택담보대출,BECBLB0202,가계대출 2),A,2009,2022,14,연리%,None
28,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020202,주택담보대출,BECBLB0202,가계대출 2),M,200909,202310,170,연리%,None
29,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020202,주택담보대출,BECBLB0202,가계대출 2),Q,2009Q3,2023Q3,57,연리%,None
30,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020203,예·적금담보대출,BECBLB0202,가계대출 2),A,2009,2022,14,연리%,None
31,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020203,예·적금담보대출,BECBLB0202,가계대출 2),M,200909,202310,170,연리%,None
32,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020203,예·적금담보대출,BECBLB0202,가계대출 2),Q,2009Q3,2023Q3,57,연리%,None
33,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020204,보증대출,BECBLB0202,가계대출 2),A,2009,2022,14,연리%,None
34,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020204,보증대출,BECBLB0202,가계대출 2),M,200909,202310,170,연리%,None
35,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020204,보증대출,BECBLB0202,가계대출 2),Q,2009Q3,2023Q3,57,연리%,None
36,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020206,일반신용대출 3),BECBLB0202,가계대출 2),A,2009,2022,14,연리%,None
37,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020206,일반신용대출 3),BECBLB0202,가계대출 2),M,200909,202310,170,연리%,None
38,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020206,일반신용대출 3),BECBLB0202,가계대출 2),Q,2009Q3,2023Q3,57,연리%,None
39,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020207,집단대출 3),BECBLB0202,가계대출 2),A,2009,2022,14,연리%,None
40,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020207,집단대출 3),BECBLB0202,가계대출 2),M,200909,202310,170,연리%,None
41,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020207,집단대출 3),BECBLB0202,가계대출 2),Q,2009Q3,2023Q3,57,연리%,None
42,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB03,공공및기타부문대출,BECBLB01,총대출 1),A,2001,2022,22,연리%,None
43,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB03,공공및기타부문대출,BECBLB01,총대출 1),M,200109,202310,266,연리%,None
44,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB03,공공및기타부문대출,BECBLB01,총대출 1),Q,2001Q3,2023Q3,89,연리%,None
45,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB04,당좌대출 4),BECBLB01,총대출 1),A,1996,2022,27,연리%,None
46,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB04,당좌대출 4),BECBLB01,총대출 1),M,199601,202310,334,연리%,None
47,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB04,당좌대출 4),BECBLB01,총대출 1),Q,1996Q1,2023Q3,111,연리%,None
48,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020208,고정형 주택담보대출,BECBLB020202,주택담보대출,A,2013,2022,10,연리%,None
49,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020208,고정형 주택담보대출,BECBLB020202,주택담보대출,M,201301,202310,130,연리%,None
50,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020208,고정형 주택담보대출,BECBLB020202,주택담보대출,Q,2013Q1,2023Q3,43,연리%,None
51,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020210,전세자금대출,BECBLB020204,보증대출,A,2015,2022,8,연리%,None
52,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020210,전세자금대출,BECBLB020204,보증대출,M,201501,202310,106,연리%,None
53,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020210,전세자금대출,BECBLB020204,보증대출,Q,2015Q1,2023Q3,35,연리%,None
54,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020209,변동형 주택담보대출,BECBLB020202,주택담보대출,A,2013,2022,10,연리%,None
55,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020209,변동형 주택담보대출,BECBLB020202,주택담보대출,M,201301,202310,130,연리%,None
56,121Y015,1.3.3.2.2. 예금은행 대출금리(잔액 기준),Group1,계정항목,BECBLB020209,변동형 주택담보대출,BECBLB020202,주택담보대출,Q,2013Q1,2023Q3,43,연리%,None

In [132]:
# 예금은행 대출금리 - 잔액 기준 - 고정형주택담보대출
fixed_loan_interest_rate_balance = api.get_statistic_search(통계표코드="121Y015", 주기="M", 검색시작일자="201301", 검색종료일자="202310", 통계항목코드1="BECBLB020208", translate=False)
fixed_loan_interest_rate_balance = return_final_df(fixed_loan_interest_rate_balance, "M", "fixed_loan_interest_rate_balance")
fixed_loan_interest_rate_balance.tail()

           fixed_loan_interest_rate_balance
TIME
2023-06-01                             3.47
2023-07-01                              3.5
2023-08-01                             3.53
2023-09-01                             3.56
2023-10-01                              3.6

In [133]:
# 예금은행 대출금리 - 잔액 기준 - 변동형주택담보대출
variable_loan_interest_rate_balance = api.get_statistic_search(통계표코드="121Y015", 주기="M", 검색시작일자="201301", 검색종료일자="202310", 통계항목코드1="BECBLB020209", translate=False)
variable_loan_interest_rate_balance = return_final_df(variable_loan_interest_rate_balance, "M", "variable_loan_interest_rate_balance")
variable_loan_interest_rate_balance.tail()

           variable_loan_interest_rate_balance
TIME
2023-06-01                                 4.7
2023-07-01                                4.69
2023-08-01                                 4.7
2023-09-01                                4.72
2023-10-01                                4.74

In [134]:
# 예금은행 대출금리 - 잔액 기준 - 전세자금대출
lease_loan_interest_rate_balance = api.get_statistic_search(통계표코드="121Y015", 주기="M", 검색시작일자="201501", 검색종료일자="202310", 통계항목코드1="BECBLB020210", translate=False)
lease_loan_interest_rate_balance = return_final_df(lease_loan_interest_rate_balance, "M", "lease_loan_interest_rate_balance")
lease_loan_interest_rate_balance.tail()

           lease_loan_interest_rate_balance
TIME
2023-06-01                             5.26
2023-07-01                             5.22
2023-08-01                             5.19
2023-09-01                             5.17
2023-10-01                             5.16

In [138]:
# c_514Y003 = api.get_statistic_item_list(통계표코드="514Y003")
# c_514Y003

# 대출행태서베이(대출수요)-국내은행-가계(일반)
loan_demand = api.get_statistic_search(통계표코드="514Y003", 주기="Q", 검색시작일자="2002Q1", 검색종료일자="2023Q4", 통계항목코드1="CC03", translate=False)
loan_demand = return_final_df(loan_demand, "Q", "loan_demand")
loan_demand.tail()

           loan_demand
TIME
2022-12-01         -19
2023-03-01         -11
2023-06-01           0
2023-09-01          -6
2023-12-01           0

In [142]:
bank_finance = pd.concat([household_credit, demand_deposit_turnover_rate, saving_deposit_turnover_rate, standard_interest_rate, usa_interest_rate, saving_interest_rate_new, saving_interest_rate_balance, fixed_loan_interest_rate_new, variable_loan_interest_rate_new, lease_loan_interest_rate_new, fixed_loan_interest_rate_balance, variable_loan_interest_rate_balance, lease_loan_interest_rate_balance, loan_demand], axis=1)
bank_finance.to_csv("bank_finance.csv")

# 3. income_expense 테이블

In [43]:
# c_200Y002

In [51]:
nominal_GNI = api.get_statistic_search(통계표코드="200Y002", 주기="Q", 검색시작일자="1961Q1", 검색종료일자="2023Q3", 통계항목코드1="20111", translate=False)
nominal_GNI = return_final_df(nominal_GNI, "Q", "nominal_GNI")
nominal_GNI.tail()

           nominal_GNI
TIME
2022-09-01        -0.3
2022-12-01         0.4
2023-03-01         2.7
2023-06-01        -0.2
2023-09-01         0.5

In [52]:
real_GNI = api.get_statistic_search(통계표코드="200Y002", 주기="Q", 검색시작일자="1961Q1", 검색종료일자="2023Q3", 통계항목코드1="20112", translate=False)
real_GNI = return_final_df(real_GNI, "Q", "real_GNI")
real_GNI.tail()

           real_GNI
TIME
2022-09-01     -0.4
2022-12-01        0
2023-03-01      1.9
2023-06-01     -0.7
2023-09-01      1.6

In [67]:
word_901Y031 = api.get_statistic_word(용어="지니계수")
word_901Y031['용어설명'].values[0]

'이탈리아의 통계학자이자 인구학자인 지니(Corrado Gini)에 의해 고안된 소득분포의 불평등 정도를 측정하는 지표이다. <그림 1>\n지니계수는 위 그래프에서 A/(A+B) 부분을 나타낸다. 이는 로렌츠곡선과 소득의 완전 균등분배를 나타내는 대각선 사이의 면적이 얼마나 되는가를 비율로 나타낸 것이다. 지니계수가 0에 가까울수록 소득격차가 작은 것을, 1에 가까울수록 소득격차가 큰 것을 나타낸다.'

In [68]:
# c_901Y031 = api.get_statistic_item_list(통계표코드="901Y031")
# c_901Y031

gini_coefficient = api.get_statistic_search(통계표코드="901Y031", 주기="A", 검색시작일자="2011", 검색종료일자="2021", 통계항목코드1="I38A", 통계항목코드2="10", translate=False)
gini_coefficient = return_final_df(gini_coefficient, "A", "gini_coefficient")
gini_coefficient

           gini_coefficient
TIME
2011-12-01            0.418
2012-12-01            0.411
2013-12-01            0.401
2014-12-01            0.397
2015-12-01            0.396
2016-12-01            0.402
2017-12-01            0.406
2018-12-01            0.402
2019-12-01            0.404
2020-12-01            0.405
2021-12-01            0.405

In [54]:
# c_200Y044 = api.get_statistic_item_list(통계표코드="200Y044")
# c_200Y044
nominal_durable_goods_expense = api.get_statistic_search(통계표코드="200Y044", 주기="Q", 검색시작일자="1970Q1", 검색종료일자="2023Q3", 통계항목코드1="10101", translate=False)
nominal_durable_goods_expense = return_final_df(nominal_durable_goods_expense, "Q", "nominal_durable_goods_expense")
nominal_durable_goods_expense.tail()

           nominal_durable_goods_expense
TIME
2022-09-01                       25611.4
2022-12-01                       25182.5
2023-03-01                       25581.1
2023-06-01                       26027.5
2023-09-01                       25666.6

In [55]:
# c_200Y045 = api.get_statistic_item_list(통계표코드="200Y045")
# c_200Y045
real_durable_goods_expense = api.get_statistic_search(통계표코드="200Y045", 주기="Q", 검색시작일자="1970Q1", 검색종료일자="2023Q3", 통계항목코드1="10101", translate=False)
real_durable_goods_expense = return_final_df(real_durable_goods_expense, "Q", "real_durable_goods_expense")
real_durable_goods_expense.tail()

           real_durable_goods_expense
TIME
2022-09-01                    25376.4
2022-12-01                    24979.5
2023-03-01                    25450.5
2023-06-01                    25557.2
2023-09-01                    24988.6

In [56]:
nominal_semi_durable_goods_expense = api.get_statistic_search(통계표코드="200Y044", 주기="Q", 검색시작일자="1970Q1", 검색종료일자="2023Q3", 통계항목코드1="10201", translate=False)
nominal_semi_durable_goods_expense = return_final_df(nominal_semi_durable_goods_expense, "Q", "nominal_semi_durable_goods_expense")
nominal_semi_durable_goods_expense.tail()

           nominal_semi_durable_goods_expense
TIME
2022-09-01                            24225.6
2022-12-01                              23138
2023-03-01                            24281.7
2023-06-01                              24289
2023-09-01                            23968.7

In [59]:
real_semi_durable_goods_expense = api.get_statistic_search(통계표코드="200Y045", 주기="Q", 검색시작일자="1970Q1", 검색종료일자="2023Q3", 통계항목코드1="10201", translate=False)
real_semi_durable_goods_expense = return_final_df(real_semi_durable_goods_expense, "Q", "real_semi_durable_goods_expense")
real_semi_durable_goods_expense.tail()

           real_semi_durable_goods_expense
TIME
2022-09-01                         22036.3
2022-12-01                         20797.4
2023-03-01                         21112.8
2023-06-01                         20850.6
2023-09-01                         20674.3

In [60]:
nominal_non_durable_goods_expense = api.get_statistic_search(통계표코드="200Y044", 주기="Q", 검색시작일자="1970Q1", 검색종료일자="2023Q3", 통계항목코드1="10301", translate=False)
nominal_non_durable_goods_expense = return_final_df(nominal_non_durable_goods_expense, "Q", "nominal_non_durable_goods_expense")
nominal_non_durable_goods_expense.tail()

           nominal_non_durable_goods_expense
TIME
2022-09-01                           57698.8
2022-12-01                           57816.4
2023-03-01                           57393.9
2023-06-01                           57488.8
2023-09-01                           57957.4

In [61]:
real_non_durable_goods_expense = api.get_statistic_search(통계표코드="200Y045", 주기="Q", 검색시작일자="1970Q1", 검색종료일자="2023Q3", 통계항목코드1="10301", translate=False)
real_non_durable_goods_expense = return_final_df(real_non_durable_goods_expense, "Q", "real_non_durable_goods_expense")
real_non_durable_goods_expense.tail()

           real_non_durable_goods_expense
TIME
2022-09-01                        48498.3
2022-12-01                        48377.1
2023-03-01                        47572.7
2023-06-01                        47667.8
2023-09-01                        47046.5

In [69]:
income_expense = pd.concat([nominal_GNI, real_GNI, gini_coefficient, nominal_durable_goods_expense, real_durable_goods_expense, nominal_semi_durable_goods_expense, real_semi_durable_goods_expense, nominal_non_durable_goods_expense, real_non_durable_goods_expense], axis=1)
income_expense.to_csv("income_expense.csv")

In [24]:
# c_151Y003 = api.get_statistic_item_list(통계표코드="151Y003")
# c_151Y003
# bank_loan = api.get_statistic_search(통계표코드="151Y003", 주기="M", 검색시작일자="200612", 검색종료일자="202309", 통계항목코드1="11110A0", translate=False)
# bank_loan.head()